package net.jpnock.privateworlds.database;

public enum DB_RETURN_CODE 
{
	SUCCESSFUL,
	WORLD_ALREADY_EXISTS,
	WORLD_DOES_NOT_EXIST,
	WORLD_DOES_NOT_EXIST_OR_NOT_INVITED,
	INTERNAL_SERVER_ERROR,
	REPORT_SQL_EXCEPTION
}
